"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let year = 1976;
// year = false;
console.log(year);
let age = 0x2b;
console.log(age);
let name = 'Ham';
// name = 10;
console.log(name);
